apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: America/New_York
          volumeMounts:
            - name: site
              mountPath: /usr/share/nginx/html
              readOnly: true
          readinessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 10
            periodSeconds: 20
      volumes:
        - name: site
          configMap:
            name: weather-site
